UAIDesarrolloArquitectura/Controllers/ABMController.cs
using BLL;
using DAL;
using Services;
using Services.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using UAIDesarrolloArquitectura.Models.ViewModel;


namespace UAIDesarrolloArquitectura.Controllers
{
    public class ABMController : Controller
    {
        DAL_User dal_user = new DAL_User();
        public ActionResult ABMUsuarios()
        {
            if (!SessionManager.IsLogged())
            {
                return RedirectToAction("Login", "Login");
            }
            if (SessionManager.GetInstance.User.Name == "Administrador")
            {
                List<User> usersList = dal_user.getUsers();
                foreach (User user in usersList)
                {
                    user.Email = PasswordEncrypter.DecryptData(user.Email);
                }
                return View(usersList);
            }
            else return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public ActionResult AddUser(string Name, string Surname, int DNI, string Email, string Password)
        {
            string Hash = PasswordEncrypter.EncryptPassword(Password);
            string emailHash = PasswordEncrypter.EncryptData(Email);
            dal_user.RegisterUser(Name, Surname, DNI, emailHash, Hash);
            BLL_CheckDigitsManager checkDigitsManager = new BLL_CheckDigitsManager();
            checkDigitsManager.SetCheckDigits();
            List<User> usersList = dal_user.getUsers();
            foreach (User user in usersList)
            {
                user.Email = PasswordEncrypter.DecryptData(user.Email);
            }
            return View("ABMUsuarios", usersList);
        }
        [HttpPost]
        public ActionResult RemoveUser(User pUser)
        {
            dal_user.DeleteUser(pUser);
            BLL_CheckDigitsManager checkDigitsManager = new BLL_CheckDigitsManager();
            checkDigitsManager.SetCheckDigits();
            List<User> usersList = dal_user.getUsers();
            foreach (User user in usersList)
            {
                user.Email = PasswordEncrypter.DecryptData(user.Email);
            }
            return View("ABMUsuarios", usersList);
        }
        [HttpPost]
        public ActionResult UpdateUser(User pUser)
        {
            dal_user.UpdateUser(pUser, false);
            BLL_CheckDigitsManager checkDigitsManager = new BLL_CheckDigitsManager();
            checkDigitsManager.SetCheckDigits();
            List<User> usersList = dal_user.getUsers();
            foreach (User user in usersList)
            {
                user.Email = PasswordEncrypter.DecryptData(user.Email);
            }
            return View("ABMUsuarios", usersList);
        }
    }
}

UAIDesarrolloArquitectura/Controllers/BackupController.cs
using Antlr.Runtime.Tree;
using BLL;
using DAL;
using Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using UAIDesarrolloArquitectura.Models.ViewModel;
using WebGrease.Activities;


namespace UAIDesarrolloArquitectura.Controllers
{
    public class BackupController : Controller
    {
        public ActionResult ErrorDV()
        {
            if (!SessionManager.IsLogged())
            {
                return RedirectToAction("Login", "Login");
            }
            return View("CorruptDatabaseMessage", BLL_CheckDigitsManager.GetErrors());
        }
        public ActionResult Backup()
        {
            DataBaseServices.BackupDatabase();
            var model = new BackupViewModel
            {
                BackupSuccess = true,
                Message = "El respaldo de la base de datos se creo con exito."
            };
            return View("BackupRestore", model);
        }
        [HttpPost]
        public ActionResult Restore(string path, string ReturnUrl)
        {
            //Le pide al que se encarga de la base de datos de restaurarla mandandole la ruta del archivo que necesita
            //El encargado le dice si se puedo hacer o no
            bool IsSuccess = DataBaseServices.RestoreDatabase(path);
            //El controlador notifica en el diccionario en la clave IsSuccess si se pudo hacer o no para que la vista lo obtenga
            TempData["IsSuccess"] = IsSuccess;
            if (ReturnUrl == "/Backup/CorrupDatabaseMessage")
            {
                return View("Login");
            }
            else return Redirect(ReturnUrl);
        }
        public ActionResult SetCheckDigits()
        {
            BLL_CheckDigitsManager checkDigitsManager = new BLL_CheckDigitsManager();
            checkDigitsManager.SetCheckDigits();
            ViewData["SetCheckDigitsIsSuccess"] = true;
            return View("CorruptDatabaseMessage");
        }
        public ActionResult BackupRestore()
        {
            if (!SessionManager.IsLogged())
            {
                return RedirectToAction("Login", "Login");
            }
            else return View("BackupRestore");
        }
    }
}

UAIDesarrolloArquitectura/Controllers/HomeController.cs
using BLL;
using DAL;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UAIDesarrolloArquitectura.ServicePrecios;
using Services.Models; // agregado para Robot

namespace UAIDesarrolloArquitectura.Controllers
{
    public class HomeController : Controller
    {
        private readonly BLL_Robot _bllRobot = new BLL_Robot(); // BLL para robots y estados

        private ActionResult RequireLogin()
        {
            if (!SessionManager.IsLogged())
            {
                return RedirectToAction("Login", "Login");
            }
            return null;
        }

        public ActionResult Startup()
        {
            return View("Index");
        }
        [HttpGet]
        public ActionResult Index()
        {
            return View("Index");
        }

        // Nueva acción para Landing de clientes
        [HttpGet]
        public ActionResult Robots()
        {
            var guard = RequireLogin(); if (guard != null) return guard;
            int uid = SessionManager.GetInstance.User.id;
            IList<Robot> robots = _bllRobot.GetRobotsForUser(uid);
            ViewBag.EstadosRobot = _bllRobot.GetEstadosRobot();
            return View("Robots", robots);
        }

        // Nueva acción para la página "Nosotros" / AboutUs
        [HttpGet]
        public ActionResult Nosotros()
        {
            return View("AboutUs");
        }

        // Nueva acción para la página "Contacto" / Contact
        [HttpGet]
        public ActionResult Contact()
        {
            return View("Contact");
        }

        // Nueva acción para la página "Privacy"
        [HttpGet]
        public ActionResult Privacy()
        {
            return View("Privacy");
        }

        public ActionResult Plans()
        {
            var servicioPrecios = new ObtPrecios();
            var precios = servicioPrecios.ObtenerPrecios();
            ViewBag.Precios = precios;
            return View("Plans");
        }

        public ActionResult Bitacora()
        {
            return View("Bitacora");
        }

        public ActionResult Logout()
        {
            DAL_User dalUser = new DAL_User();
            if (SessionManager.IsLogged())
            {
                dalUser.EventLog(SessionManager.GetInstance.User.id, DateTime.Now.ToString(), "Cierre de sesión", "Se cerró sesión");
                BLL_CheckDigitsManager bll_dvmanager = new BLL_CheckDigitsManager();
                bll_dvmanager.SetCheckDigits();
            }
            SessionManager.logout();
            return View("Index");
        }

        // Nueva acción para cargar mantenimientos de robots
        [HttpGet]
        public ActionResult Mantenimientos()
        {
            var guard = RequireLogin(); if (guard != null) return guard;
            int uid = SessionManager.GetInstance.User.id;
            var dalRobot = new DAL_Robot();
            var dalList = dalRobot.GetRobotsByUser(uid);
            var mantenimientosPorRobot = new Dictionary<int, IList<MantenimientoRobot>>();
            foreach (var r in dalList)
            {
                var mts = dalRobot.GetMaintenances(r.Id, null, null,100);
                mantenimientosPorRobot[r.Id] = mts;
            }
            ViewBag.Robots = dalList; // lista de robots para referencias
            return View("Mantenimientos", mantenimientosPorRobot);
        }

        // Nueva acción para Telemetría (reemplaza Estadísticas)
        [HttpGet]
        public ActionResult Telemetria()
        {
            var guard = RequireLogin(); if (guard != null) return guard;
            int uid = SessionManager.GetInstance.User.id;
            var dalRobot = new DAL_Robot();
            var robots = dalRobot.GetRobotsByUser(uid);
            var telemetriaPorRobot = new Dictionary<int, IList<TelemetriaRobot>>();
            foreach (var r in robots)
            {
                var tel = dalRobot.GetTelemetry(r.Id, null, null,100);
                telemetriaPorRobot[r.Id] = tel;
            }
            ViewBag.Robots = robots;
            return View("Telemetria", telemetriaPorRobot);
        }

        // Nueva acción ContactUs para sidebar
        [HttpGet]
        public ActionResult ContactUs()
        {
            var guard = RequireLogin(); if (guard != null) return guard;
            return View("ContactUs");
        }
    }
}

UAIDesarrolloArquitectura/Controllers/IdiomaController.cs
using DAL;
using Services.Idioma;
using Services;
using System.Collections.Generic;
using System.Web.Mvc;
using UAIDesarrolloArquitectura.Models;
using BLL;
using System;

namespace UAIDesarrolloArquitectura.Controllers
{
    public class IdiomaController : Controller
    {
        DAL_Language dal_language = new DAL_Language();
        // GET: Idioma
        static Services.LanguageService service;

        public void InitializeController()
        {
            if (service == null)
            {
                service = new Services.LanguageService();
                DAL_Language dal = new DAL_Language();
                List<Language> aux = dal.GetLanguages();
                service.InitializeService(aux);
            }
        }

        public LanguageService GetService()
        {
            return service;
        }

        // POST: Language
        [HttpPost]
        public RedirectResult SetLanguage(LanguageDTO data)
        {
            string valorSeleccionado = data.Valor;
            string urlActual = data.Url;

            // Asegurar redireccion valida: usar ruta relativa del referrer si es absoluta
            if (!string.IsNullOrEmpty(urlActual))
            {
                Uri uri;
                if (Uri.TryCreate(urlActual, UriKind.Absolute, out uri))
                {
                    // Conservar path, query y fragmento
                    urlActual = uri.PathAndQuery + uri.Fragment;
                }
            }
            else
            {
                urlActual = "/"; // fallback
            }

            BLL_CheckDigitsManager checkDigitsManager = new BLL_CheckDigitsManager();

            if (SessionManager.IsLogged())
            {
                SessionManager.GetInstance.User.LanguageId = int.Parse(valorSeleccionado);
                DAL_User dal_user = new DAL_User();
                dal_user.UpdateUser(SessionManager.GetInstance.User, true);
                checkDigitsManager.SetCheckDigits();
            }

            service.ChangeLanguage(valorSeleccionado);
            return Redirect(urlActual);
        }

        public ActionResult ABMIdioma()
        {
            if (!SessionManager.IsLogged())
            {
                return RedirectToAction("Login", "Login");
            }
            // Solo usuario webmaster por Id (14)
            var u = SessionManager.GetInstance.User;
            if (u == null || u.id !=14)
            {
                return RedirectToAction("Index", "Home");
            }
            List<Language> langList = dal_language.GetLanguages();
            return View(langList);
        }

        [HttpPost]
        public ActionResult AddLanguage(string name)
        {
            // Solo usuario Id14
            if (!SessionManager.IsLogged() || SessionManager.GetInstance.User?.id !=14)
            {
                return new HttpStatusCodeResult(403);
            }
            List<Language> langList = dal_language.GetLanguages();
            List<string> tags = new List<string>();

            foreach (Translate tr in langList[0].ListTranslate)
            {
                tags.Add(tr.Name);
            }

            dal_language.AddLanguage(name);
            int id = dal_language.GetLastId();
            dal_language.AddTags(id, tags);

            List<int> ids = new List<int>();
            foreach (Language l in langList)
            {
                ids.Add(l.Id);
            }

            ids.Add(id);
            dal_language.AddTagForItself(ids, name);
            langList = dal_language.GetLanguages();

            return View("ABMIdioma", langList);
        }

        [HttpPost]
        public ActionResult AddWord(string tag)
        {
            // Solo usuario Id14
            if (!SessionManager.IsLogged() || SessionManager.GetInstance.User?.id !=14)
            {
                return new HttpStatusCodeResult(403);
            }
            if (string.IsNullOrWhiteSpace(tag))
            {
                ModelState.AddModelError("tag", "Tag requerido");
            }
            else
            {
                List<Language> langList = dal_language.GetLanguages();
                List<int> ids = new List<int>();
                foreach (Language l in langList) ids.Add(l.Id);
                dal_language.AddTagForItself(ids, tag.Trim());
            }
            return View("ABMIdioma", dal_language.GetLanguages());
        }

        [HttpPost]
        public ActionResult UpdateTranslate(int id, string tag, string text)
        {
            // Solo usuario Id14
            if (!SessionManager.IsLogged() || SessionManager.GetInstance.User?.id !=14)
            {
                return new HttpStatusCodeResult(403);
            }
            dal_language.ModifyTranslate(id, tag, text);
            List<Language> langList = dal_language.GetLanguages();
            return View("ABMIdioma", langList);
        }

        [HttpPost]
        public ActionResult UpdatePage(int id, string tag)
        {
            if (!SessionManager.IsLogged())
            {
                return RedirectToAction("Login", "Login");
            }

            // Solo usuario Id14
            if (SessionManager.GetInstance.User?.id ==14)
            {
                List<Language> langList = dal_language.GetLanguages();
                Language lang = langList.Find(x => x.Id == id);
                Translate tran = lang.ListTranslate.Find(x => x.Name == tag);

                ViewBag.tran = tran;
                ViewBag.lan = lang;

                return View(tran);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

UAIDesarrolloArquitectura/Views/Home/AboutUs.cshtml
@using Services.Models
@model List<string>
<!DOCTYPE html>
<html lang="es">
@{
    ViewBag.Title = "AgroMinds";
    Services.Idioma.Translator translator = new Services.Idioma.Translator();
    UAIDesarrolloArquitectura.Controllers.IdiomaController lC = new UAIDesarrolloArquitectura.Controllers.IdiomaController();
    lC.InitializeController();
    Services.LanguageService service = lC.GetService();
    service.Susbcribe(translator);
    if (Services.SessionManager.IsLogged())
    {
        service.ChangeLanguage((Services.SessionManager.GetInstance.User.LanguageId).ToString());
    }
    else
    {
        if (!service.SelectedLanguageExists()) { service.ChangeLanguage("1"); }
    }
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AgroMinds</title>
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Chivo:wght@400;700&display=swap" rel="stylesheet">
    <style>
        /* Cookie consent modal styles (blue theme) consistent with other views */
        #cookieConsentModal {
            position: fixed;
            bottom: 20px;
            left: 20px;
            right: 20px;
            max-width: 980px;
            margin: 0 auto;
            background: #1E88E5;
            color: #ffffff;
            border-radius: 8px;
            box-shadow: 6px 24px rgba(0,0,0,0.2);
            padding: 18px;
            display: none;
            z-index: 9999;
            font-family: 'Chivo', Arial, sans-serif;
        }
        #cookieConsentModal a { color: #BBDEFB; text-decoration: underline; }
        #cookieConsentModal .consent-content { display: flex; gap: 12px; align-items: center; }
        #cookieConsentModal p { margin: 0; color: #ffffff; }
        #cookieConsentModal .actions { margin-left: auto; display: flex; gap: 8px; }
        #cookieConsentModal .btn { padding: 8px 12px; border-radius: 4px; border: none; cursor: pointer; font-weight: 600; }
        #cookieConsentModal .btn-accept { background: #0D47A1; color: white; }
        #cookieConsentModal .btn-decline { background: rgba(255,255,255,0.12); color: #ffffff; border: 1px solid rgba(255,255,255,0.18); }
        @@media (max-width: 600px) {
            #cookieConsentModal { left: 12px; right: 12px; bottom: 12px; padding: 12px; }
            #cookieConsentModal .consent-content { flex-direction: column; align-items: stretch; }
            #cookieConsentModal .actions { margin-left: 0; justify-content: flex-end; }
        }
    </style>
</head>

<body>
    <nav class="barra">
        @if (Services.SessionManager.IsLogged())
        {
            <div id="opciones" class="opciones">
                <a href="@Url.Action("Logout", "Home")">@translator.GetTraduction(service, "Logout")</a>
                <a style="display:none;" id="bitacora" href="@Url.Action("Bitacora", "Bitacora")">@translator.GetTraduction(service, "Log")</a>
                <a style="display:none;" id="abmusuarios" href="@Url.Action("ABMUsuarios", "ABM")">@translator.GetTraduction(service, "ManageUser")</a>
                <a style="display:none;" id="restore" href="@Url.Action("BackupRestore", "Backup")">@translator.GetTraduction(service, "Restoredb")</a>
                <a style="display:none;" id="1001" href="@Url.Action("ABMIdioma", "Idioma")">@translator.GetTraduction(service, "ManageLanguage")</a>
                <a style="display:none;" id="1002" href="@Url.Action("CrearPerfiles", "CrearPerfiles")">@translator.GetTraduction(service, "CreateProfile")</a>
                <a style="display:none;" id="1003" href="@Url.Action("AsignarPerfil", "AsignarPerfil")">@translator.GetTraduction(service, "AssignProfile")</a>
                <script type="text/javascript">
                    @foreach (string permission in Services.SessionManager.GetInstance.User.permissionList)
                    {
                        <text>document.getElementById('@permission').style.display = 'block';</text>
                    }
                </script>
            </div>
            <div class="opciones">
                <p style="color:white;">@translator.GetTraduction(service, "Welcome"), @Services.SessionManager.GetInstance.User.Name</p>
            </div>
        }
        else
        {
            <a href="@Url.Action("Login", "Login")">@translator.GetTraduction(service, "Login")</a>
            <a href="@Url.Action("Register", "Register")">@translator.GetTraduction(service, "Register")</a>
        }

        <form>
            <select id="option" onchange="enviarValor()">
                @foreach (Services.Idioma.Language l in service.GetLanguages())
                {
                    if (service.SelectedLanguage.Id == l.Id)
                    {
                        <option value="@l.Id" selected="selected">@translator.GetTraduction(service, l.Name)</option>
                    }
                    else
                    {
                        <option value="@l.Id">@translator.GetTraduction(service, l.Name)</option>
                    }
                }
            </select>
        </form>
    </nav>

    <header>
        <h1 style="color:#2E7D32;">AgroMinds</h1>
    </header>
    <nav class="menu-secundario">
        <a href="@Url.Action("Index", "Home")">@translator.GetTraduction(service, "Main")</a>
        <a href="@Url.Action("Plans", "Home")">@translator.GetTraduction(service, "Plans")</a>
        <a href="@Url.Action("Nosotros", "Home")">@translator.GetTraduction(service, "AboutUs")</a>
        <a href="@Url.Action("Contact", "Home")">@translator.GetTraduction(service, "Contact")</a>
    </nav>
    <div class="container" style="display:flex;flex-wrap:wrap;justify-content:center;align-items:center;gap:40px;margin-top:40px;">
        <div id="descripcion" style="max-width:500px;text-align:left;line-height:1.6;">
            <h2>@translator.GetTraduction(service, "AboutUsHeading")</h2>
            <p>@translator.GetTraduction(service, "AboutUsP1")</p>
            <p>@translator.GetTraduction(service, "AboutUsP2")</p>
            <p>@translator.GetTraduction(service, "AboutUsP3")</p>
            <p>@translator.GetTraduction(service, "AboutUsP4")</p>
            <p>@translator.GetTraduction(service, "AboutUsP5")</p>
        </div>
        <div style="flex-shrink:0;">
            <img src="~/assets/team.jpg" alt="AgroMinds Logo"
                 style="max-width:300px;height:auto;border-radius:10px;" />
        </div>
    </div>

    <footer style="background-color:#2E7D32; color:white; padding:10px; text-align:center;">©2026 AgroMinds — @translator.GetTraduction(service, "AllRightsReserved")</footer>


    <!-- Cookie consent modal markup -->
    <div id="cookieConsentModal" role="dialog" aria-labelledby="cookieConsentTitle" aria-describedby="cookieConsentDesc">
        <div class="consent-content">
            <div style="max-width:760px;">
                <strong id="cookieConsentTitle">Consentimiento de cookies</strong>
                <p id="cookieConsentDesc">Utilizamos cookies propias y de terceros para mejorar su experiencia. Si acepta, usaremos cookies para análisis y personalización. Puede cambiar su preferencia en cualquier momento.</p>
                <a href="@Url.Action("Privacy", "Home")">Leer más</a>
            </div>
            <div class="actions">
                <button id="declineCookies" class="btn btn-decline">Rechazar</button>
                <button id="acceptCookies" class="btn btn-accept">Aceptar</button>
            </div>
        </div>
    </div>

    <script src="~/Scripts/scriptIdioma.js"></script>

    <script>
        (function () {
            var key = 'cookieConsentAgrominds';
            function hasConsent() {
                try { return localStorage.getItem(key) === 'accepted'; } catch (e) { return false; }
            }
            function setConsent(value) {
                try { localStorage.setItem(key, value); } catch (e) { }
            }
            function showModal() {
                var m = document.getElementById('cookieConsentModal');
                if (m) m.style.display = 'block';
            }
            function hideModal() {
                var m = document.getElementById('cookieConsentModal');
                if (m) m.style.display = 'none';
            }

            document.addEventListener('DOMContentLoaded', function () {
                if (!hasConsent()) {
                    showModal();
                }

                var acceptBtn = document.getElementById('acceptCookies');
                var declineBtn = document.getElementById('declineCookies');

                if (acceptBtn) acceptBtn.addEventListener('click', function () { setConsent('accepted'); hideModal(); });
                if (declineBtn) declineBtn.addEventListener('click', function () { setConsent('declined'); hideModal(); });
            });
        })();
    </script>
</body>
</html>